### PR TITLE
Remove ART

### LINKED ISSUE #47: Cannot find module 'art/core/path.js'.
Following a basic setup, I get the following error running on Jest 22:

```
 FAIL  frontend/native/screens/__tests__/concentration_screen_spec.js
  ● Test suite failed to run

    Cannot find module 'art/core/class.js' from 'Path.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/react-native-mock-render/build/components/ART/Path.js:1:104)
```

Searching around in the codebase, I don't see any files that match `art/core/class.js`. I've had to comment out the `ART` component in `react-native.js` on line 13.

Anyone know what's going on there?

### PR DESCRIPTION
**Pull request by sonicdoe**
ART has been removed in React Native v0.62. See https://github.com/facebook/react-native/commit/9a0ebe0abaec7b59bdefe63cd7d392737ab20160 and [@react-native-community/art](https://github.com/react-native-community/art). Fixes #47.

### CODE REVIEW

**Comment by caroaguilar** [comment]
@root-devs @lelandrichardson Is there a chance this PR can be merged and get a new npm release soon? React Native 0.63 is out as well and this package is an important part of our suite of testing and we need to migrate to latest RN. I'd really appreciate if we can this out! 🙏

**Comment by leonardoprangetw** [comment]
approve please

**Comment by fabioxd20** [comment]
@root-devs @lelandrichardson can you approve this ? 🙏

**Comment by igoriols** [comment]
Hi @root-devs @lelandrichardson , we are working to migrate our react-native version to 0.63.2. The approval of this PR is crucial to our migration. Can you approve this, please?

**Comment by jakequade** [comment]
@root-devs @lelandrichardson What's stopping this from being merged?

**Comment by AnyIdeasAds** [comment]
anyone? Approve?

**Review by kukiron — APPROVED** [review]

**Comment by dochsu** [comment]
Can this change be merged to allow us to migration to react-native version 0.63.2?  We currently have our tests disabled to allow our CI to pass.  Not optimal but our tests are legacy and will require some effort to rewrite.

**Comment by sjransom** [comment]
@root-devs @kukiron 
Is there a reason this can't be merged currently?

**Comment by mrdulin** [comment]
I folked this fixed commit and published to my own npm registry. 

https://www.npmjs.com/package/dl-react-native-mock-render

Why published to npm registry instead of installing from github? Because I met this issue https://github.com/yarnpkg/yarn/issues/7212  at CI phrase of github action

**Comment by dac245** [comment]
> I folked this fixed commit and published to my own npm registry.
> 
> https://www.npmjs.com/package/dl-react-native-mock-render
> 
> Why published to npm registry instead of installing from github? Because I met this issue [yarnpkg/yarn#7212](https://github.com/yarnpkg/yarn/issues/7212) at CI phrase of github action

I tried using this but seems like the repo is not there anymore. Is there a different repo?

**Pull request closed without merging**
